### PR TITLE
Serialization/unserialization error handling

### LINKED ISSUE #8: json_decode not throw an exception
https://github.com/RiskioFr/idempotency-module/blob/334f4428f4db51f4276e0189109b2ac7f8ec5c65/src/Serializer/Serializer.php#L23

Throw a custom exception when json_decode fail. It will not throw an exception, you must use `json_last_error()` to get error code (or `JSON_ERROR_NONE`)

See : http://php.net/manual/fr/function.json-last-error.php

### PR DESCRIPTION
**Pull request by neeckeloo**
This PR fixes #8 issue.

### CODE REVIEW

File: src/Serializer/Serializer.php [hunk 1]
```diff
@@ -3,28 +3,53 @@
...
+
+        return $result;
     }
 
     public function unserialize(string $idempotentRequest) : IdempotentRequest
     {
-        $decoded = (array) json_decode($idempotentRequest);
+        $result = json_decode($idempotentRequest, true);
+
+        if (!$result) {
```
Comment (DamienGilbrin) [inline src/Serializer/Serializer.php]: Maybe use this : 
```
if (json_last_error() !== JSON_ERROR_NONE)
```

**Review by DamienGilbrin — CHANGES_REQUESTED** [review]
